### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by papplampe** [guillaumechereau/noc#1]
I managed to get noc to work under windows. I used msys2 and the packages mingw-w64-i686-glew,
mingw-w64-i686-glfw.
To compile it I used 
    gcc -s -O3 -o test_turtle tests\turtle.c noc_turtle.c -Wall -lglfw3 -lglew32 -I.

Everything draws fine but sun, blowfish objs, shapes, stencil and colors samples are flickering however.

![noc_windows](https://cloud.githubusercontent.com/assets/858269/8130832/163664b4-1116-11e5-881f-47f51e97f1a3.PNG)

**Comment by guillaumechereau** [comment]
I will try it out and see if I can fix the flickering.  Thanks for testing!

**Comment by guillaumechereau** [comment]
I made some small changes in the code that might fixed the bug.  Let me know if it still does not work.

**Comment by papplampe** [comment]
Yeah, that did work. Looks good now.
