### ISSUE TITLE
Unable to get multiple file extension in filter

### ISSUE THREAD

**Issue by henryborchers** [guillaumechereau/noc#3]
I'm unable to filter multiple file extension with noc_file_dialog_open(). 

Instead of just using a single file extension per selection, like here:

"png\0*.png\0jpeg\0*.jpeg\0All Files\0*.*"

I'd like to filter a category of extensions. For example, Image formats and video formats.

This seems to work for Windows when I do...

`noc_file_dialog_open(NOC_FILE_DIALOG_OPEN, "Video Files\0*.mov;*.mp4;*.mpg;*.mkv\0All Files\0*.*\0", NULL, NULL);`

This seems to only work in Windows but not on other OSs.

I have some luck on OSX in that it doesn't even give you the option to select filters.

`noc_file_dialog_open(NOC_FILE_DIALOG_OPEN, "Video Files\0*.mov\0Matroska\0*.mkv\0MPEG\0*.mpg\0MPEG-4\0*.mp4\0", NULL, NULL);`

This works as expected for the native dialog box by showing all the categories at once. 

However, I can't figure out how to group the right string that GTK2 on Ubuntu parses multiple file extensions together. 

Is there a single format that I should be using to group my extensions into categories or am I going to have to create different string filters for each OS?

**Comment by guillaumechereau** [comment]
I just pushed a commit that add support for ';' separated patterns in the gtk version.
Can you try it out?

**Comment by henryborchers** [comment]
Thanks for this. This is a very useful header only library. 

Sorry I didn't see you had updated this. I'm impressed. 

Anyways, I just tried this new version on OS X but no luck. I tried the following:

``
noc_file_dialog_open(NOC_FILE_DIALOG_OPEN, "Video Files\0*.mov;*.mp4;*.mpg;*.mkv\0All Files\0*.*\0", NULL, NULL);
``

and..


``
noc_file_dialog_open(NOC_FILE_DIALOG_OPEN, "Video Files\0*.mov;*.mp4;*.mpg;*.mkv\0", NULL, NULL);
``

and it filter everything out.

**Comment by guillaumechereau** [comment]
Right, I only changed the linux version code.   The osx code also need to be updated to support this syntax.  I will try to have a look when I have time.

**Comment by henryborchers** [comment]
Awesome!

**Comment by guillaumechereau** [comment]
I didn't test it much, please let me know if you have any trouble with it.

**Comment by henryborchers** [comment]
Still not working for me on OSX. Sorry... :-(

The string ```"Video Files\0*.mov;*.mp4;*.mpg;*.mkv\0"``` selects no formats.

Am I doing something wrong?

**Comment by guillaumechereau** [comment]
I just tested with this exact string, and it seems to work.  Can you past the exact part of the code you are using?

**Comment by henryborchers** [comment]
Hmm... I think I was still using a version that was cached. Now I'm having trouble compiling but I'll have to see why that's happening when I get back from holiday.

**Comment by henryborchers** [comment]
Okay, sorry for not getting back to you sooner. Just got back from holiday. The most recent version works fine for on my Windows machine but I'm unable to compile this on Clang on a OSX.

In the NOC_FILE_DIALOG_OSX version you are missing the following line.

`char buf[128], *patterns;`

**Comment by henryborchers** [comment]
When you add that line back in, it works!

**Comment by guillaumechereau** [comment]
Thanks! I have no idea how I pushed this.  I usually work on linux so I might have messed up on the commit.  I committed a patch. Hopefully it works, I haven't tested it!

**Comment by henryborchers** [comment]
This works! I often work between Windows and Mac and occasionally run a Ubuntu desktop to see that everything works there. I completely get missing a test for a system you are not currently on.

Thanks for fixing this. I'm relatively new to C but I'm building a personal project in it anyways and had a need to create a demo to show people. This header only library really saved me a lot of time. Thanks!
