### ISSUE TITLE
Libraries are permissively licensed

### ISSUE THREAD

**Issue by r-lyeh** [guillaumechereau/noc#4]
Quoting from the README `A list of public domain libraries for C/C++, inspired by the stb libraries.`.
However, all the libs are MIT licensed.

**Comment by guillaumechereau** [comment]
In my understanding MIT is a public domain license, isn't it?  I will change the README file to avoid confusion.

**Comment by r-lyeh** [comment]
They're different. The closest license to PD is either The Unlicense or The Zero-BSD clause.
Brief comparison here: https://choosealicense.com/licenses/
