### ISSUE TITLE
Default path and name broken on Win32 for noc_file_dialog_open

### ISSUE THREAD

**Issue by mathkr** [guillaumechereau/noc#8]
Hey.

Default path as well as default name aren't getting set corrently in the OPENFILENAME struct.
Here's the fixed version:

```
const char *noc_file_dialog_open(int flags,
                                 const char *filters,
                                 const char *default_path,
                                 const char *default_name)
{

    OPENFILENAME ofn;       // common dialog box structure
    char szFile[260];       // buffer for file name
    int ret;

    // init default file name
    if (default_name)
        strncpy(szFile, default_name, sizeof(szFile) - 1);
    else
        szFile[0] = '\0';

    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.lpstrFile = szFile;
    ofn.nMaxFile = sizeof(szFile);
    ofn.lpstrFilter = filters;
    ofn.nFilterIndex = 1;
    ofn.lpstrFileTitle = NULL;
    ofn.nMaxFileTitle = 0;
    ofn.lpstrInitialDir = (LPSTR)default_path;
    ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

    if (flags & NOC_FILE_DIALOG_OPEN)
        ret = GetOpenFileName(&ofn);
    else
        ret = GetSaveFileName(&ofn);

    free(g_noc_file_dialog_ret);
    g_noc_file_dialog_ret = ret ? strdup(szFile) : NULL;
    return g_noc_file_dialog_ret;
}
```

These are the important bits:
```
    // init default file name
    if (default_name)
        strncpy(szFile, default_name, sizeof(szFile) - 1);
    else
        szFile[0] = '\0';

    // ...

    ofn.lpstrInitialDir = (LPSTR)default_path;
```

**Comment by guillaumechereau** [comment]
Thanks!  Do you want to make a proper pull request so that you get credited ?

**Comment by guillaumechereau** [comment]
Actually I just realize someone already made a pull request for the same issue a while ago.  I almost never use windows.  Can you check if this PR is correct:
https://github.com/guillaumechereau/noc/pull/7

**Comment by mathkr** [comment]
I've created a pull request.

I changed another thing which - I presume - you also want to have fixed since it changes the behaviour #compared to the other platform versions:

Windows common file dialogs by default set the current working directory to the save/load directory. To prevent this you can set the flag OFN_NOCHANGEDIR.
See the documentation here: https://docs.microsoft.com/de-de/windows/desktop/api/commdlg/ns-commdlg-tagofna

Pull request: #9

#7 only fixes the default directory, btw. It doesn't set the default file name.

**Comment by guillaumechereau** [comment]
OK, I merged, thanks!
